# Please use a nightly rustfmt for these settings.
imports_granularity = "module"
wrap_comments = true

# The code blocks get a scrollbar if they are wider than this.
max_width = 81

# Allow all constructs to take up max_width columns.
use_small_heuristics = "Max"
